### ISSUE TITLE
Is there a npm package for this module?

### ISSUE THREAD

**Issue by aalexgabi** [madmurphy/cookies.js#10]
I can't seem to find one.

In case this is not published, what do you think about publishing it?

**Comment by madmurphy** [comment]
Hi Aalex!

I have no idea actually, I am just the guy who wrote the code.

It would be great to publish it though! Unfortunately I will have no time for some weeks. What would you think about publishing it yourself?

**Comment by kirly-af** [comment]
@madmurphy, @aalexgabi 
There's already this module: https://www.npmjs.com/package/doc-cookies
I opened https://github.com/bibliolabs/docCookies/issues/7 to upgrade to revision 3 and @evanmuller seems to be ok with that.

Maybe in the future one of these 2 repos should be deprecated?

**Comment by kirly-af** [comment]
See https://github.com/madmurphy/cookies.js/pull/11

**Comment by madmurphy** [comment]
@kirly-af

Many thanks!

> Maybe in the future one of these 2 repos should be deprecated?

Well, I guess as the author I should not deprecate myself ;)

**Comment by evanmuller** [comment]
@madmurphy glad @kirly-af found the original author of this code. I updated the npm package to point to your repo. I can make you a collaborator and even take myself and bibliolabs off the package if you want to take over ownership. Do you have an npm username?

**Comment by madmurphy** [comment]
@evanmuller Thank you and sorry for the late answer! Unfortunately I do not have a npm username. But feel free to use your repo! P.S. I just realeased an update btw.

**Comment by markcellus** [comment]
So just to clarify, which repository have we settled on as the repo associated with the [doc-cookies](https://www.npmjs.com/package/doc-cookies) and [cookies.js](https://www.npmjs.com/package/cookies.js) package? And which npm package is considered the one we should all use? 

https://github.com/jasonkarns/doc-cookies seems outdated and doesn't have the typescript declaration file.

It's been a convention to have the repo name be the same as the npm package name. Let me know if I can help out at all!
