### ISSUE TITLE
The new "clear" function doesn't work in IE11.

### ISSUE THREAD

**Issue by Serrin** [madmurphy/cookies.js#13]
The new "clear" function doesn't work in IE11 and the loading of the library casues a JS error in the loading time.

Please check the compatibility of the for..of on this page:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of
(ECMAScript 2015 (6th Edition, ECMA-262))

There is another way to do this:
```
  clear: function (sPath, sDomain) {
    var that = this;
    this.keys().forEach(function (sKey) { that.removeItem(sKey, sPath, sDomain); });
  } 
```
The forEach can be replaced with a simple for loop.

**Comment by madmurphy** [comment]
@Serrin Thank you! Fixed.

**Comment by Serrin** [comment]
@madmurphy  Not at all!

Now working in IE11.
