### ISSUE TITLE
How to minify it?

### ISSUE THREAD

**Issue by rvalitov** [madmurphy/cookies.js#14]
Hello!
I'd like to contribute, but I don't see any instructions how you minify the code? Do you use tasks from Grunt, Gulp or do you use UglifyJS natively? May be you should publish your configuration file?

**Comment by madmurphy** [comment]
@rvalitov

Hi!

Normally I use https://javascript-minifier.com/. Consider that **cookies.js** is such a small script that any other tool would do the job.

If you have any pull request you may also submit only the non-minified version of the library, I would do the rest.

--madmurphy

**Comment by rvalitov** [comment]
Ok, thank you for a prompt response! One more question, so my PR will be correctly prepared. Usually a minified file has extension `.min.js`, so in your case it should be `cookies.min.js`. Can you please explain why do you prefer to use another syntax like `cookies_min.js`?

**Comment by madmurphy** [comment]
@rvalitov

> Usually a minified file has extension `.min.js`, so in your case it should be `cookies.min.js`. Can you please explain why do you prefer to use another syntax like `cookies_min.js`?

This library has been around for a while. At the time there were not so strong conventions about the suffix that a minified js file should have. Most library had `-min.js`, others had `_min.js`. But you just made me realize it would be time to rename the minified file to `cookies.min.js`.

--madmurphy

**Comment by rvalitov** [comment]
Thank you. I will make my PR in the upcoming days.
