### ISSUE TITLE
HttpOnly support

### ISSUE THREAD

**Issue by kirsn** [madmurphy/cookies.js#7]
I didn't see the support for HttpOnly, so attempted a PR (https://github.com/madmurphy/cookies.js/pull/6).

**Comment by madmurphy** [comment]
@kirsn Thanks! I just merged your commit.

**Comment by madmurphy** [comment]
@kirsn Thanks for your contribution. But from what I know `HttpOnly` [cannot be available to javascript](https://stackoverflow.com/questions/14691654/set-a-cookie-to-httponly-via-javascript) (and that's fair, since it's the meaning of the “HttpOnly” flag).

**Comment by kirsn** [comment]
@madmurphy .. that obvious fact escaped me, when I attempted this :) 
Yes, makes sense. Will close this issue.
